name: New Singer Submission
description: Submit a new singer/voicebank to the SVS Index
title: "[Singer] "
labels: ["submission", "singer"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing! 
        
        **Use the [Singer Editor](https://openutau.github.io/svs-index/submit.html) to generate valid JSON**, then paste it below.
        
        The editor helps you:
        - Validate all required fields
        - Check singer ID uniqueness
        - Ensure proper JSON structure
        - Avoid common mistakes

  - type: textarea
    id: singer_json
    attributes:
      label: Singer JSON
      description: |
        Complete singer object in JSON format. Must include:
        - id: unique hyphenated identifier (5+ chars, lowercase)
        - names: object with at least 'en' key
        - owners: array of owner names
        - authors: array of author/voice provider names
        - variants: array of variant objects (each with id, names, and at least one URL)
        - homepage_url (optional)
        - profile_image_url (optional)
      placeholder: |
        {
          "id": "hatsune-miku",
          "names": {
            "en": "Hatsune Miku",
            "ja": "初音ミク"
          },
          "owners": ["Crypton Future Media"],
          "authors": ["Saki Fujita"],
          "homepage_url": "https://ec.crypton.co.jp/pages/prod/vocaloid/cv01",
          "variants": [
            {
              "id": "hatsune-miku-v4x",
              "names": {
                "en": "Hatsune Miku V4X"
              },
              "file_url": null,
              "download_page_url": "https://ec.crypton.co.jp/pages/prod/vocaloid/cv01",
              "tags": ["vocaloid4"]
            }
          ]
        }
      render: json
    validations:
      required: true
