name: New Singer Submission
description: Submit a new singer/voicebank to the SVS Index
title: "[Singer] "
labels: ["submission", "singer"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing! Please fill out all required fields below.
        All submissions will be reviewed before merging.

  - type: input
    id: id
    attributes:
      label: Unique ID
      description: "Lowercase, hyphenated identifier (e.g., hatsune-miku)"
    validations:
      required: true

  - type: input
    id: name_en
    attributes:
      label: Name (English)
      description: "English name of the singer"
    validations:
      required: true

  - type: input
    id: name_ja
    attributes:
      label: Name (Japanese)
      description: "Japanese name (optional)"

  - type: input
    id: name_zh
    attributes:
      label: Name (Chinese)
      description: "Chinese name (optional)"

  - type: textarea
    id: owners
    attributes:
      label: Owners
      description: "List of owners, one per line"
    validations:
      required: true

  - type: textarea
    id: authors
    attributes:
      label: Authors
      description: "List of authors/voice providers, one per line"
    validations:
      required: true

  - type: input
    id: homepage_url
    attributes:
      label: Homepage URL
      description: "Official homepage (optional)"

  - type: input
    id: profile_image_url
    attributes:
      label: Profile Image URL
      description: "Direct link to profile image (optional)"

  - type: textarea
    id: variants
    attributes:
      label: Variants (JSON)
      description: |
        List of voicebank variants in JSON array format. Each variant must have:
        - id: unique identifier
        - names: object with at least 'en' key
        - download_url: direct download link or null
        - manual_download_url: manual download page or null
        - tags: optional array of tags
      render: json
    validations:
      required: true
