name: New Software Submission
description: Submit a new software/tool to the SVS Index
title: "[Software] "
labels: ["submission", "software"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing! Please fill out all required fields below.
        All submissions will be reviewed before merging.

  - type: input
    id: id
    attributes:
      label: Unique ID
      description: "Lowercase, hyphenated identifier (e.g., vocaloid4)"
    validations:
      required: true

  - type: input
    id: name_en
    attributes:
      label: Name (English)
      description: "English name of the software"
    validations:
      required: true

  - type: input
    id: name_ja
    attributes:
      label: Name (Japanese)
      description: "Japanese name (optional)"

  - type: input
    id: name_zh
    attributes:
      label: Name (Chinese)
      description: "Chinese name (optional)"

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: "Software category"
      options:
        - host
        - host_extension
        - utility
    validations:
      required: true

  - type: textarea
    id: developers
    attributes:
      label: Developers
      description: "List of developers, one per line"
    validations:
      required: true

  - type: input
    id: homepage_url
    attributes:
      label: Homepage URL
      description: "Official homepage (optional)"

  - type: input
    id: download_page_url
    attributes:
      label: Download Page URL
      description: "Manual download page (optional, use null if not available)"

  - type: input
    id: file_url
    attributes:
      label: Direct Download URL
      description: "Direct download link (optional, use null if not available)"

  - type: input
    id: tags
    attributes:
      label: Tags
      description: "Comma-separated tags (optional)"
