name: New Software Submission
description: Submit a new software/tool to the SVS Index
title: "[Software] "
labels: ["submission", "software"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing! Please fill out all required fields below.
        All submissions will be reviewed before merging.

  - type: input
    id: id
    attributes:
      label: Unique ID
      description: "Lowercase, hyphenated identifier (e.g., vocaloid4)"
      placeholder: "vocaloid4"
    validations:
      required: true

  - type: input
    id: name_en
    attributes:
      label: Name (English)
      description: "English name of the software"
      placeholder: "Vocaloid4"
    validations:
      required: true

  - type: input
    id: name_ja
    attributes:
      label: Name (Japanese)
      description: "Japanese name (optional)"
      placeholder: ""

  - type: input
    id: name_zh
    attributes:
      label: Name (Chinese)
      description: "Chinese name (optional)"
      placeholder: ""

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: "Software category"
      options:
        - host
        - host_extension
        - utility
    validations:
      required: true

  - type: textarea
    id: developers
    attributes:
      label: Developers
      description: "List of developers, one per line"
      placeholder: |
        Yamaha Corporation
    validations:
      required: true

  - type: input
    id: homepage_url
    attributes:
      label: Homepage URL
      description: "Official homepage (optional)"
      placeholder: "https://www.vocaloid.com/"

  - type: input
    id: download_url
    attributes:
      label: Download URL
      description: "Direct download link (optional, use null if not available)"
      placeholder: "https://example.com/download"

  - type: input
    id: manual_download_url
    attributes:
      label: Manual Download URL
      description: "Manual download page (optional, use null if not available)"
      placeholder: "https://example.com/download-page"

  - type: input
    id: tags
    attributes:
      label: Tags
      description: "Comma-separated tags (optional)"
      placeholder: "host, vocaloid, commercial"
